### ISSUE TITLE
file is not a database

### ISSUE THREAD

**Issue by jokechat** [howie6879/w2b#1]
```bash
╭─jokechat@jokechatPro in ~/develop/opencode/w2b on master ✘ (origin/master)
╰$ pipenv shell
Launching subshell in virtual environment…
 . /Users/jokechat/.local/share/virtualenvs/w2b-_67A4XFc/bin/activate
╭─jokechat@jokechatPro in ~/develop/opencode/w2b on master ✘ (origin/master)
╰$  . /Users/jokechat/.local/share/virtualenvs/w2b-_67A4XFc/bin/activate
(w2b) ╭─jokechat@jokechatPro in ~/develop/opencode/w2b on master ✘ (origin/master)
╰$ pipenv run python w2b/run.py
/Users/jokechat/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/74e9cd9415960a0a518568392a707ba1/Message/msg_1.db
Traceback (most recent call last):
  File "w2b/run.py", line 78, in <module>
    run()
  File "w2b/run.py", line 67, in run
    db_path = get_target_db_path()
  File "/Users/jokechat/develop/opencode/w2b/w2b/sqlite_db.py", line 37, in get_target_db_path
    f"""SELECT count(*) FROM sqlite_master WHERE type="table" AND name = "{msg_table_name}" """
pysqlcipher3.dbapi2.DatabaseError: file is not a database

```

详细报错信息如上,我把db路径打印出来了,并且SQLite 浏览器照着文档可以浏览进去了,这个原因是执行sql问题么?

**Comment by howie6879** [comment]
可以用软件看到里面的数据么？

**Comment by jokechat** [comment]
> 可以用软件看到里面的数据么？

是的.软件中正常浏览,不太懂python语法,查了两天,确认是仅仅修改了以下的变量

S_ACCOUNT_ID
R_ACCOUNT_ID
RAW_KEY
PC_NAME

**Comment by howie6879** [comment]
你需要好好debug一下，看你错误还是配置不大对，或者数据库位置不对，不过我已经弄了个简单方案了，直接上手用

看这里：https://github.com/howie6879/examiner

**Comment by jokechat** [comment]
看到了,很强大
新方案挺好用
